Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -47,6 +47,12 @@ for BUILDPACK in $(cat $1/.buildpacks); do
     chmod -f +x $dir/bin/{detect,compile,release} || true
 
     framework=$($dir/bin/detect $1)
+    
+    echo "=====> Framework $framework"
+    
+    x=$?
+    
+    echo "=====> Error code: $x"
 
     if [ $? == 0 ]; then
       echo "=====> Detected Framework: $framework"
